#!/usr/bin/env bash
# installs nginx and configure to display Hello World

sudo apt-get -y update
dufo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
