#!/usr/bin/env bash
# installs nginx and configure to display Hello World

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo -n "Hello World!" > /var/www/html/index.html
sudo service nginx start
