#!/usr/bin/env bash
# configure nginx to contain custom HTTP header X-Served-By
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
   
   add_header X-Served-By \$hostname;

}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart 
