#!/usr/bin/env bash
# configure nginx to contain custom HTTP header X-Served-By

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
   
   add_header X-Served-By \$hostname;

}" > default

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart 
