#!/usr/bin/env bash
# create mysql backup

if [ $# -eq 0 ]; then
  echo "Error: Please provide the MySQL root password as an argument."
  exit 1
fi

backup_date=$(date +'%d-%m-%Y')

sudo mysqldump -u root -p"$1" --all-databases > backup.sql

sudo tar -czvf "$backup_date.tar.gz" backup.sql

echo "MySQL backup created successfully: $backup_date.tar.gz"
