#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4

cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
sudo service nginx restart
