#!/usr/bin/env bash
# display PID along with process name containing bash

for pid in /proc/*/; do
  pid=${pid%*/}
  pid=${pid##*/}
  if [[ -f "/proc/$pid/cmdline" ]]; then
    cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline")
    if [[ "$cmdline" == *"bash"* ]]; then
      echo "$pid $(cat /proc/$pid/status | grep 'Name:' | awk '{print $2}')"
    fi
  fi
done
