#!/usr/bin/env bash
# display the content of /etc/passwd im a story form

while IFS=: read -r username password uid gid gecos homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
