#!/usr/bin/env bash
# a bsh script that displays Best School 10 times
# but fo rthe 9th iteration says hi on a new line
count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	count=$((count+1))
done
