#!/usr/bin/env bash
# displays the content of the current directory in a list format

for file in *
do
    if [ "${file:0:1}" != "." ] && [ "${file:0:1}" != "_" ] && [ -f "$file" ]
    then
        filename="${file#*-}"
        echo "$filename"
    fi
done
