#!/usr/bin/env bash
# script resolves local host to 127.0.0.2
# resolves facebook.com to 8.8.8.8
#sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sudo sed -i 'a\8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
