#!/usr/bin/env bash
# script resolves local host to 127.0.0.2
# resolves facebook.com to 8.8.8.8
#sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sudo sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
